### ISSUE TITLE
Request for the Github `eva` reserved name

### ISSUE THREAD

**Issue by evaporei** [matt-usurp/grok#3]
Hey Matt! Sorry for creating an unrelated issue to the repo, I didn't know if you would read your e-mail, so I've sent the same request here too 😄 

I want to know if you would be willing to give out the `eva` organization name here on Github https://github.com/eva to me, because it's not currently in use and it only has one public archive repo there.

If not that's fine too! Thanks in advance 😊

**Comment by matt-usurp** [comment]
Hi @evaporei, I have had a fair few people come after the organisation because it looks inactive. There are a fair few active private repositories within the organisation that are used as dependencies. I will be in touch by email in a few weeks (as I am on holiday) to discuss this better 💯
